Eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('home_module.urls')),
    path('product/', include('project_module.urls')),
    path('', include('account_module.urls')),
    path('article/', include('article_module.urls')),
    path('contact/', include('contact_module.urls')),
    path('user/', include('user_panel.urls')),
    path('order/', include('paymant_module.urls')),
    path('admin/', admin.site.urls,name='admin_panel'),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.ArticleListView.as_view(), name='article_page' ),
    path('cat/<str:category>',views.ArticleListView.as_view(), name='article_category_component' ),
    path('comment-add',views.ArticleCommentAdd, name='article_comment_add' ),
    path('<pk>/',views.ArticleDetailView.as_view(), name='article_detail' ),
]

user_panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.UserPanelDashboard.as_view(),name='user_panel'),
    path('change-pass',views.ChangePasswordClass.as_view(),name='change_pass'),
    path('edit-profile',views.EditProfileClass.as_view(),name='edit_profile'),
    path('shopping-panel',views.shopping_panel,name='shopping_panel'),
    path('delete_item_shopping',views.delete_item_from_shopping,name='delete_item_shopping'),
    path('payment-history',views.PaymentHistory.as_view(),name='payment_history'),
    path('payment-detail',views.PaymentDetail.as_view(),name='payment_detail'),
]

article_module/models.py
from django.db import models
from account_module.models import User

# Create your models here.


class ArticleCategory(models.Model):
    parent = models.ForeignKey(to='ArticleCategory', blank=True, null=True, verbose_name='والد', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='عنوان')
    url_title = models.CharField(max_length=200, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال/غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    short_description = models.TextField(verbose_name='توضیح کوتاه')
    text = models.TextField(verbose_name='توضیح اصلی')
    slug = models.SlugField(max_length=100, db_index=True, allow_unicode=True,verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/article/', verbose_name='تصویر')
    is_active = models.BooleanField(default=True, verbose_name='فعال/غیرفعال')
    article_category = models.ManyToManyField(to=ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, verbose_name='نویسنده', on_delete=models.CASCADE, null=True,editable=False)
    created_date = models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ثبت',editable=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        
class ArticleComment(models.Model):
    article = models.ForeignKey(Article, verbose_name='عنوان مقاله', on_delete=models.CASCADE)
    parent = models.ForeignKey('ArticleComment', verbose_name="والد",null=True,blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="کاربر", on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name="متن نظر")

    class Meta:
        verbose_name = 'نظر مقاله'
        verbose_name_plural = 'نظرات مقاله'

    def __str__(self):
        return str(self.user)

article_module/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic import DetailView
from . import models
# Create your views here.


class ArticleListView(ListView):
    model = models.Article
    template_name = 'article_module/article_page.html'
    paginate_by = 1
    
    def get_queryset(self,**kwargs):
        query = super().get_queryset(**kwargs)
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(article_category__url_title__iexact = category_name)
        return query
        

def article_category_component(request: HttpRequest):
    article_category = models.ArticleCategory.objects.prefetch_related('articlecategory_set').filter(is_active=True,parent_id=None)
    context = {'main_categorys':article_category}
    return render(request,'article_module/article_component/article_category_component.html',context)


class ArticleDetailView(DetailView):
    model = models.Article
    template_name = 'article_module/article_detail_page.html'
    def get_queryset(self,**kwargs):
        query =  super().get_queryset(**kwargs)
        query = query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article:models.Article = kwargs.get('object')
        context['comments'] = models.ArticleComment.objects.filter(article_id=article.id,parent=None).order_by('-created_date').prefetch_related('articlecomment_set')
        context['comments_count'] = models.ArticleComment.objects.filter(article_id=article.id).count()
        return context

def ArticleCommentAdd(request:HttpRequest):
    if request.user.is_authenticated:
        comment = request.GET.get('comment')
        parent_id = request.GET.get('parent_id')
        article_id = request.GET.get('article_id')
        new_comment = models.ArticleComment(text=comment,parent_id=parent_id,article_id=article_id,user_id=request.user.id)
        new_comment.save()
        context = {
            'comments': models.ArticleComment.objects.filter(article_id=article_id,parent=None).order_by('-created_date').prefetch_related('articlecomment_set'),
            'comments_count': models.ArticleComment.objects.filter(article_id=article_id).count()
        }
        return render(request, 'article_module/includes/comments_include.html', context)
    return HttpResponse('response')

article_module/templates/article_module/article_detail_page.html
{% extends "shared/_layot.html" %}
{% load render_partial %}
{% load thumbnail %}
{% load poll_extras %}

{% block title %}مقاله{% endblock title %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">{{article.title}}</h2>
                        <div class="single-blog-post">
                            <h3>{{article.title}}</h3>
                            <div class="post-meta">
                                <ul>
                                    <li><i class="fa fa-user"></i>{{article.author}}</li>
                                    <li><i class="fa fa-clock-o"></i>{{article.created_date | show_jalali_time}}</li>
                                    <li><i class="fa fa-calendar"></i>{{article.created_date | show_jalali_date}}</li>
                                </ul>
                                <span>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-half-o"></i>
                                </span>
                            </div>
                            <a href="">
                                {% thumbnail article.image "862x398" crop='center' quality=70 as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
                            </a>
                            <p>
                                {{article.short_description}}
                            </p>
                            <p>
                                {{article.text}}
                            </p>
                        </div>
                    </div>
                    <div class="media commnets">
                        <a class="pull-right" href="#">
                            {% if article.author.avatar %}
                                {% thumbnail article.author.avatar "121x86" crop='center' quality=70 as im %}
                                    <img class="media-object" src="{{ im.url }}">
                                {% endthumbnail %}
                                {% else %}
                                    <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                            {% endif %}
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading">نویسنده: {{article.author}}</h4>
                            <p>{{article.author.about_user}}</p>
                        </div>
                    </div>
                    <div class="response-area" id="comments_area">
                        <h2>نظر ها ({{comments_count}})</h2>
                        {% for comment in comments %}
                                <ul class="media-list">
                                    <li class="media" id="single_comment_box_{{comment.id}}">
                                        <a class="pull-right" href="#">
                                            {% thumbnail comment.user.avatar "121x86" crop='center' quality=70 as im %}
                                                <img src="{{ im.url }}">
                                            {% endthumbnail %}
                                        </a>
                                        <div class="media-body">
                                            <ul class="sinlge-post-meta">
                                                <li><i class="fa fa-user"></i>{{comment.user}}</li>
                                                <li><i class="fa fa-clock-o"></i>{{comment.created_date | show_jalali_time}}</li>
                                                <li><i class="fa fa-calendar"></i>{{comment.created_date | show_jalali_date}}</li>
                                            </ul>
                                            <p>{{comment.text}}</p>
                                            <a class="btn btn-primary" onclick="GetParent({{comment.id}})"><i class="fa fa-reply"></i>پاسـخ</a>
                                        </div>
                                    </li>
                                </ul>					
                                {% for reply in comment.articlecomment_set.all %}
                                    <ul class="media-list second-media" id="single_comment_box_{{comment.id}}">
                                        <li class="media">
                                            <a class="pull-right" href="#">
                                                {% thumbnail reply.user.avatar "121x86" crop='center' quality=70 as im %}
                                                    <img src="{{ im.url }}">
                                                {% endthumbnail %}
                                            </a>
                                            <div class="media-body">
                                                <ul class="sinlge-post-meta">
                                                    <li><i class="fa fa-user"></i>{{reply.user}}</li>
                                                    <li><i class="fa fa-clock-o"></i>{{reply.created_date | show_jalali_time}}</li>
                                                    <li><i class="fa fa-calendar"></i>{{reply.created_date | show_jalali_date}}</li>
                                                </ul>
                                                <p>{{reply.text}}</p>
                                            </div>
                                        </li>
                                    </ul>					
                                {% endfor %}
                            {% endfor %}
                    </div>
                    <div class="replay-box" id='comment_form'>
                        {% if request.user.is_authenticated %}
                        <div class="row">
                            <div class="col-sm-12">
                                <input type="hidden" id='parent_id' value=''>
                                <h2>نظـر خود را بنویسیـد</h2>
                                <div class="text-area">
                                    <div class="blank-arrow">
                                        <label>متن پیام</label>
                                    </div>
                                    <span>*</span>
                                    <textarea name="message" rows="11" id='commenttext'></textarea>
                                    <a class="btn btn-primary" href="" onclick="ArticleCommentSend({{article.id}})">ارسـال نظـر</a>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="alert alert-warning">برای درج نظر باید <a href="{% url "login_page" %}">لاگین</a> کنید</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {%render_partial 'article_module.views.article_category_component'%}
                        <div class="shipping text-center"><!--shipping-->
                            <img src="/static/images/home/shipping.jpg" alt="">
                        </div><!--/shipping-->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

article_module/templates/article_module/article_page.html
{% extends "shared/_layot.html" %}
{% load thumbnail %}
{% load poll_extras %}
{% load render_partial %}

{% block title %}مقالات{% endblock title %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">آخریـن اخبـار</h2>
                        {{date}}
                        {% for article in article_list %}
                        <div class="single-blog-post">
                            <h3>{{article.title}}</h3>
                            <div class="post-meta">
                                <ul>
                                    <li><i class="fa fa-user"></i>{{article.author}}</li>
                                    <li><i class="fa fa-clock-o"></i>{{article.created_date | show_jalali_time}}</li>
                                    <li><i class="fa fa-calendar"></i>{{article.created_date | show_jalali_date}}</li>
                                </ul>
                                <span>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-half-o"></i>
                                </span>
                            </div>
                            <a href="">
                                {% thumbnail article.image "862x398" crop='center' quality=70 as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
                            </a>
                            <p>{{article.short_description}}</p>
                            <a class="btn btn-primary" href="{% url "article_detail" pk=article.id %}">ادامـه مطلب</a>
                        </div>
                        {% endfor %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for pageNumber in paginator.page_range %}
                                <li class="{% if page_obj.number == pageNumber %} active {% endif %}"><a href="?page={{ pageNumber }}">{{ pageNumber }}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number}}">بعدی</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                
                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial 'article_module.views.article_category_component' %}
                        <div class="shipping text-center"><!--shipping-->
                            <img src="/static/images/home/shipping.jpg" alt="">
                        </div><!--/shipping-->
                    </div>
                </div>
                
            </div>
        </div>
    </section>
{% endblock content %}